/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssessmentsRouteImport } from './routes/assessments'
import { Route as CalibrationRouteImport } from './routes/calibration'
import { Route as CapabilityMapRouteImport } from './routes/capability-map'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CompetencyMatrixRouteImport } from './routes/competency-matrix'
import { Route as CyclesRouteImport } from './routes/cycles'
import { Route as DevelopmentPlansRouteImport } from './routes/development-plans'
import { Route as GapAnalysisRouteImport } from './routes/gap-analysis'
import { Route as LearningPathsRouteImport } from './routes/learning-paths'
import { Route as MentoringRouteImport } from './routes/mentoring'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as ProgressionRouteImport } from './routes/progression'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TeamRulesRouteImport } from './routes/team-rules'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as TrainingNeedsRouteImport } from './routes/training-needs'
import { Route as UsersRouteImport } from './routes/users'
import { Route as ArchitectsArchitectIdRouteImport } from './routes/architects.$architectId'
import { Route as ArchitectsArchitectIdIndexRouteImport } from './routes/architects.$architectId.index'
import { Route as ArchitectsArchitectIdEvolutionRouteImport } from './routes/architects.$architectId.evolution'
import { Route as ArchitectsArchitectIdRoadmapRouteImport } from './routes/architects.$architectId.roadmap'
import { Route as ArchitectsArchitectIdStatementRouteImport } from './routes/architects.$architectId.statement'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsRoute = AssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const CalibrationRoute = CalibrationRouteImport.update({
  id: '/calibration',
  path: '/calibration',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilityMapRoute = CapabilityMapRouteImport.update({
  id: '/capability-map',
  path: '/capability-map',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetencyMatrixRoute = CompetencyMatrixRouteImport.update({
  id: '/competency-matrix',
  path: '/competency-matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const CyclesRoute = CyclesRouteImport.update({
  id: '/cycles',
  path: '/cycles',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentPlansRoute = DevelopmentPlansRouteImport.update({
  id: '/development-plans',
  path: '/development-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const GapAnalysisRoute = GapAnalysisRouteImport.update({
  id: '/gap-analysis',
  path: '/gap-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningPathsRoute = LearningPathsRouteImport.update({
  id: '/learning-paths',
  path: '/learning-paths',
  getParentRoute: () => rootRouteImport,
} as any)
const MentoringRoute = MentoringRouteImport.update({
  id: '/mentoring',
  path: '/mentoring',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressionRoute = ProgressionRouteImport.update({
  id: '/progression',
  path: '/progression',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRulesRoute = TeamRulesRouteImport.update({
  id: '/team-rules',
  path: '/team-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingNeedsRoute = TrainingNeedsRouteImport.update({
  id: '/training-needs',
  path: '/training-needs',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectsArchitectIdRoute = ArchitectsArchitectIdRouteImport.update({
  id: '/architects/$architectId',
  path: '/architects/$architectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectsArchitectIdIndexRoute =
  ArchitectsArchitectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ArchitectsArchitectIdRoute,
  } as any)
const ArchitectsArchitectIdEvolutionRoute =
  ArchitectsArchitectIdEvolutionRouteImport.update({
    id: '/evolution',
    path: '/evolution',
    getParentRoute: () => ArchitectsArchitectIdRoute,
  } as any)
const ArchitectsArchitectIdRoadmapRoute =
  ArchitectsArchitectIdRoadmapRouteImport.update({
    id: '/roadmap',
    path: '/roadmap',
    getParentRoute: () => ArchitectsArchitectIdRoute,
  } as any)
const ArchitectsArchitectIdStatementRoute =
  ArchitectsArchitectIdStatementRouteImport.update({
    id: '/statement',
    path: '/statement',
    getParentRoute: () => ArchitectsArchitectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRoute
  '/calibration': typeof CalibrationRoute
  '/capability-map': typeof CapabilityMapRoute
  '/compare': typeof CompareRoute
  '/competency-matrix': typeof CompetencyMatrixRoute
  '/cycles': typeof CyclesRoute
  '/development-plans': typeof DevelopmentPlansRoute
  '/gap-analysis': typeof GapAnalysisRoute
  '/learning-paths': typeof LearningPathsRoute
  '/mentoring': typeof MentoringRoute
  '/notices': typeof NoticesRoute
  '/progression': typeof ProgressionRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/team-rules': typeof TeamRulesRoute
  '/teams': typeof TeamsRoute
  '/training-needs': typeof TrainingNeedsRoute
  '/users': typeof UsersRoute
  '/architects/$architectId': typeof ArchitectsArchitectIdRouteWithChildren
  '/architects/$architectId/evolution': typeof ArchitectsArchitectIdEvolutionRoute
  '/architects/$architectId/roadmap': typeof ArchitectsArchitectIdRoadmapRoute
  '/architects/$architectId/statement': typeof ArchitectsArchitectIdStatementRoute
  '/architects/$architectId/': typeof ArchitectsArchitectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRoute
  '/calibration': typeof CalibrationRoute
  '/capability-map': typeof CapabilityMapRoute
  '/compare': typeof CompareRoute
  '/competency-matrix': typeof CompetencyMatrixRoute
  '/cycles': typeof CyclesRoute
  '/development-plans': typeof DevelopmentPlansRoute
  '/gap-analysis': typeof GapAnalysisRoute
  '/learning-paths': typeof LearningPathsRoute
  '/mentoring': typeof MentoringRoute
  '/notices': typeof NoticesRoute
  '/progression': typeof ProgressionRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/team-rules': typeof TeamRulesRoute
  '/teams': typeof TeamsRoute
  '/training-needs': typeof TrainingNeedsRoute
  '/users': typeof UsersRoute
  '/architects/$architectId/evolution': typeof ArchitectsArchitectIdEvolutionRoute
  '/architects/$architectId/roadmap': typeof ArchitectsArchitectIdRoadmapRoute
  '/architects/$architectId/statement': typeof ArchitectsArchitectIdStatementRoute
  '/architects/$architectId': typeof ArchitectsArchitectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRoute
  '/calibration': typeof CalibrationRoute
  '/capability-map': typeof CapabilityMapRoute
  '/compare': typeof CompareRoute
  '/competency-matrix': typeof CompetencyMatrixRoute
  '/cycles': typeof CyclesRoute
  '/development-plans': typeof DevelopmentPlansRoute
  '/gap-analysis': typeof GapAnalysisRoute
  '/learning-paths': typeof LearningPathsRoute
  '/mentoring': typeof MentoringRoute
  '/notices': typeof NoticesRoute
  '/progression': typeof ProgressionRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/team-rules': typeof TeamRulesRoute
  '/teams': typeof TeamsRoute
  '/training-needs': typeof TrainingNeedsRoute
  '/users': typeof UsersRoute
  '/architects/$architectId': typeof ArchitectsArchitectIdRouteWithChildren
  '/architects/$architectId/evolution': typeof ArchitectsArchitectIdEvolutionRoute
  '/architects/$architectId/roadmap': typeof ArchitectsArchitectIdRoadmapRoute
  '/architects/$architectId/statement': typeof ArchitectsArchitectIdStatementRoute
  '/architects/$architectId/': typeof ArchitectsArchitectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessments'
    | '/calibration'
    | '/capability-map'
    | '/compare'
    | '/competency-matrix'
    | '/cycles'
    | '/development-plans'
    | '/gap-analysis'
    | '/learning-paths'
    | '/mentoring'
    | '/notices'
    | '/progression'
    | '/set-password'
    | '/settings'
    | '/team'
    | '/team-rules'
    | '/teams'
    | '/training-needs'
    | '/users'
    | '/architects/$architectId'
    | '/architects/$architectId/evolution'
    | '/architects/$architectId/roadmap'
    | '/architects/$architectId/statement'
    | '/architects/$architectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessments'
    | '/calibration'
    | '/capability-map'
    | '/compare'
    | '/competency-matrix'
    | '/cycles'
    | '/development-plans'
    | '/gap-analysis'
    | '/learning-paths'
    | '/mentoring'
    | '/notices'
    | '/progression'
    | '/set-password'
    | '/settings'
    | '/team'
    | '/team-rules'
    | '/teams'
    | '/training-needs'
    | '/users'
    | '/architects/$architectId/evolution'
    | '/architects/$architectId/roadmap'
    | '/architects/$architectId/statement'
    | '/architects/$architectId'
  id:
    | '__root__'
    | '/'
    | '/assessments'
    | '/calibration'
    | '/capability-map'
    | '/compare'
    | '/competency-matrix'
    | '/cycles'
    | '/development-plans'
    | '/gap-analysis'
    | '/learning-paths'
    | '/mentoring'
    | '/notices'
    | '/progression'
    | '/set-password'
    | '/settings'
    | '/team'
    | '/team-rules'
    | '/teams'
    | '/training-needs'
    | '/users'
    | '/architects/$architectId'
    | '/architects/$architectId/evolution'
    | '/architects/$architectId/roadmap'
    | '/architects/$architectId/statement'
    | '/architects/$architectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentsRoute: typeof AssessmentsRoute
  CalibrationRoute: typeof CalibrationRoute
  CapabilityMapRoute: typeof CapabilityMapRoute
  CompareRoute: typeof CompareRoute
  CompetencyMatrixRoute: typeof CompetencyMatrixRoute
  CyclesRoute: typeof CyclesRoute
  DevelopmentPlansRoute: typeof DevelopmentPlansRoute
  GapAnalysisRoute: typeof GapAnalysisRoute
  LearningPathsRoute: typeof LearningPathsRoute
  MentoringRoute: typeof MentoringRoute
  NoticesRoute: typeof NoticesRoute
  ProgressionRoute: typeof ProgressionRoute
  SetPasswordRoute: typeof SetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  TeamRoute: typeof TeamRoute
  TeamRulesRoute: typeof TeamRulesRoute
  TeamsRoute: typeof TeamsRoute
  TrainingNeedsRoute: typeof TrainingNeedsRoute
  UsersRoute: typeof UsersRoute
  ArchitectsArchitectIdRoute: typeof ArchitectsArchitectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments': {
      id: '/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calibration': {
      id: '/calibration'
      path: '/calibration'
      fullPath: '/calibration'
      preLoaderRoute: typeof CalibrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capability-map': {
      id: '/capability-map'
      path: '/capability-map'
      fullPath: '/capability-map'
      preLoaderRoute: typeof CapabilityMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competency-matrix': {
      id: '/competency-matrix'
      path: '/competency-matrix'
      fullPath: '/competency-matrix'
      preLoaderRoute: typeof CompetencyMatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cycles': {
      id: '/cycles'
      path: '/cycles'
      fullPath: '/cycles'
      preLoaderRoute: typeof CyclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development-plans': {
      id: '/development-plans'
      path: '/development-plans'
      fullPath: '/development-plans'
      preLoaderRoute: typeof DevelopmentPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gap-analysis': {
      id: '/gap-analysis'
      path: '/gap-analysis'
      fullPath: '/gap-analysis'
      preLoaderRoute: typeof GapAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-paths': {
      id: '/learning-paths'
      path: '/learning-paths'
      fullPath: '/learning-paths'
      preLoaderRoute: typeof LearningPathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentoring': {
      id: '/mentoring'
      path: '/mentoring'
      fullPath: '/mentoring'
      preLoaderRoute: typeof MentoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progression': {
      id: '/progression'
      path: '/progression'
      fullPath: '/progression'
      preLoaderRoute: typeof ProgressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-rules': {
      id: '/team-rules'
      path: '/team-rules'
      fullPath: '/team-rules'
      preLoaderRoute: typeof TeamRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training-needs': {
      id: '/training-needs'
      path: '/training-needs'
      fullPath: '/training-needs'
      preLoaderRoute: typeof TrainingNeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architects/$architectId': {
      id: '/architects/$architectId'
      path: '/architects/$architectId'
      fullPath: '/architects/$architectId'
      preLoaderRoute: typeof ArchitectsArchitectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architects/$architectId/': {
      id: '/architects/$architectId/'
      path: '/'
      fullPath: '/architects/$architectId/'
      preLoaderRoute: typeof ArchitectsArchitectIdIndexRouteImport
      parentRoute: typeof ArchitectsArchitectIdRoute
    }
    '/architects/$architectId/evolution': {
      id: '/architects/$architectId/evolution'
      path: '/evolution'
      fullPath: '/architects/$architectId/evolution'
      preLoaderRoute: typeof ArchitectsArchitectIdEvolutionRouteImport
      parentRoute: typeof ArchitectsArchitectIdRoute
    }
    '/architects/$architectId/roadmap': {
      id: '/architects/$architectId/roadmap'
      path: '/roadmap'
      fullPath: '/architects/$architectId/roadmap'
      preLoaderRoute: typeof ArchitectsArchitectIdRoadmapRouteImport
      parentRoute: typeof ArchitectsArchitectIdRoute
    }
    '/architects/$architectId/statement': {
      id: '/architects/$architectId/statement'
      path: '/statement'
      fullPath: '/architects/$architectId/statement'
      preLoaderRoute: typeof ArchitectsArchitectIdStatementRouteImport
      parentRoute: typeof ArchitectsArchitectIdRoute
    }
  }
}

interface ArchitectsArchitectIdRouteChildren {
  ArchitectsArchitectIdEvolutionRoute: typeof ArchitectsArchitectIdEvolutionRoute
  ArchitectsArchitectIdRoadmapRoute: typeof ArchitectsArchitectIdRoadmapRoute
  ArchitectsArchitectIdStatementRoute: typeof ArchitectsArchitectIdStatementRoute
  ArchitectsArchitectIdIndexRoute: typeof ArchitectsArchitectIdIndexRoute
}

const ArchitectsArchitectIdRouteChildren: ArchitectsArchitectIdRouteChildren = {
  ArchitectsArchitectIdEvolutionRoute: ArchitectsArchitectIdEvolutionRoute,
  ArchitectsArchitectIdRoadmapRoute: ArchitectsArchitectIdRoadmapRoute,
  ArchitectsArchitectIdStatementRoute: ArchitectsArchitectIdStatementRoute,
  ArchitectsArchitectIdIndexRoute: ArchitectsArchitectIdIndexRoute,
}

const ArchitectsArchitectIdRouteWithChildren =
  ArchitectsArchitectIdRoute._addFileChildren(
    ArchitectsArchitectIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentsRoute: AssessmentsRoute,
  CalibrationRoute: CalibrationRoute,
  CapabilityMapRoute: CapabilityMapRoute,
  CompareRoute: CompareRoute,
  CompetencyMatrixRoute: CompetencyMatrixRoute,
  CyclesRoute: CyclesRoute,
  DevelopmentPlansRoute: DevelopmentPlansRoute,
  GapAnalysisRoute: GapAnalysisRoute,
  LearningPathsRoute: LearningPathsRoute,
  MentoringRoute: MentoringRoute,
  NoticesRoute: NoticesRoute,
  ProgressionRoute: ProgressionRoute,
  SetPasswordRoute: SetPasswordRoute,
  SettingsRoute: SettingsRoute,
  TeamRoute: TeamRoute,
  TeamRulesRoute: TeamRulesRoute,
  TeamsRoute: TeamsRoute,
  TrainingNeedsRoute: TrainingNeedsRoute,
  UsersRoute: UsersRoute,
  ArchitectsArchitectIdRoute: ArchitectsArchitectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
