/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssessmentsRouteImport } from './routes/assessments'
import { Route as CalibrationRouteImport } from './routes/calibration'
import { Route as CapabilityMapRouteImport } from './routes/capability-map'
import { Route as CatalogPolicyRouteImport } from './routes/catalog-policy'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CompetencyMatrixRouteImport } from './routes/competency-matrix'
import { Route as CyclesRouteImport } from './routes/cycles'
import { Route as DevelopmentPlansRouteImport } from './routes/development-plans'
import { Route as EligibilityRouteImport } from './routes/eligibility'
import { Route as GapAnalysisRouteImport } from './routes/gap-analysis'
import { Route as LearningPathsRouteImport } from './routes/learning-paths'
import { Route as MentoringRouteImport } from './routes/mentoring'
import { Route as ModelReferenceRouteImport } from './routes/model-reference'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as PlatformMetricsRouteImport } from './routes/platform-metrics'
import { Route as ProgressionRouteImport } from './routes/progression'
import { Route as ScoringRulersRouteImport } from './routes/scoring-rulers'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TeamRulesRouteImport } from './routes/team-rules'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as TextTemplatesRouteImport } from './routes/text-templates'
import { Route as TrainingNeedsRouteImport } from './routes/training-needs'
import { Route as UsersRouteImport } from './routes/users'
import { Route as VocabulariesRouteImport } from './routes/vocabularies'
import { Route as ProfessionalsProfessionalIdRouteImport } from './routes/professionals.$professionalId'
import { Route as ProfessionalsProfessionalIdIndexRouteImport } from './routes/professionals.$professionalId.index'
import { Route as ProfessionalsProfessionalIdEvolutionRouteImport } from './routes/professionals.$professionalId.evolution'
import { Route as ProfessionalsProfessionalIdRoadmapRouteImport } from './routes/professionals.$professionalId.roadmap'
import { Route as ProfessionalsProfessionalIdStatementRouteImport } from './routes/professionals.$professionalId.statement'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsRoute = AssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const CalibrationRoute = CalibrationRouteImport.update({
  id: '/calibration',
  path: '/calibration',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilityMapRoute = CapabilityMapRouteImport.update({
  id: '/capability-map',
  path: '/capability-map',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogPolicyRoute = CatalogPolicyRouteImport.update({
  id: '/catalog-policy',
  path: '/catalog-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetencyMatrixRoute = CompetencyMatrixRouteImport.update({
  id: '/competency-matrix',
  path: '/competency-matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const CyclesRoute = CyclesRouteImport.update({
  id: '/cycles',
  path: '/cycles',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentPlansRoute = DevelopmentPlansRouteImport.update({
  id: '/development-plans',
  path: '/development-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const EligibilityRoute = EligibilityRouteImport.update({
  id: '/eligibility',
  path: '/eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const GapAnalysisRoute = GapAnalysisRouteImport.update({
  id: '/gap-analysis',
  path: '/gap-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningPathsRoute = LearningPathsRouteImport.update({
  id: '/learning-paths',
  path: '/learning-paths',
  getParentRoute: () => rootRouteImport,
} as any)
const MentoringRoute = MentoringRouteImport.update({
  id: '/mentoring',
  path: '/mentoring',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelReferenceRoute = ModelReferenceRouteImport.update({
  id: '/model-reference',
  path: '/model-reference',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformMetricsRoute = PlatformMetricsRouteImport.update({
  id: '/platform-metrics',
  path: '/platform-metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressionRoute = ProgressionRouteImport.update({
  id: '/progression',
  path: '/progression',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoringRulersRoute = ScoringRulersRouteImport.update({
  id: '/scoring-rulers',
  path: '/scoring-rulers',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRulesRoute = TeamRulesRouteImport.update({
  id: '/team-rules',
  path: '/team-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TextTemplatesRoute = TextTemplatesRouteImport.update({
  id: '/text-templates',
  path: '/text-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingNeedsRoute = TrainingNeedsRouteImport.update({
  id: '/training-needs',
  path: '/training-needs',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabulariesRoute = VocabulariesRouteImport.update({
  id: '/vocabularies',
  path: '/vocabularies',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalsProfessionalIdRoute =
  ProfessionalsProfessionalIdRouteImport.update({
    id: '/professionals/$professionalId',
    path: '/professionals/$professionalId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfessionalsProfessionalIdIndexRoute =
  ProfessionalsProfessionalIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProfessionalsProfessionalIdRoute,
  } as any)
const ProfessionalsProfessionalIdEvolutionRoute =
  ProfessionalsProfessionalIdEvolutionRouteImport.update({
    id: '/evolution',
    path: '/evolution',
    getParentRoute: () => ProfessionalsProfessionalIdRoute,
  } as any)
const ProfessionalsProfessionalIdRoadmapRoute =
  ProfessionalsProfessionalIdRoadmapRouteImport.update({
    id: '/roadmap',
    path: '/roadmap',
    getParentRoute: () => ProfessionalsProfessionalIdRoute,
  } as any)
const ProfessionalsProfessionalIdStatementRoute =
  ProfessionalsProfessionalIdStatementRouteImport.update({
    id: '/statement',
    path: '/statement',
    getParentRoute: () => ProfessionalsProfessionalIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRoute
  '/calibration': typeof CalibrationRoute
  '/capability-map': typeof CapabilityMapRoute
  '/catalog-policy': typeof CatalogPolicyRoute
  '/compare': typeof CompareRoute
  '/competency-matrix': typeof CompetencyMatrixRoute
  '/cycles': typeof CyclesRoute
  '/development-plans': typeof DevelopmentPlansRoute
  '/eligibility': typeof EligibilityRoute
  '/gap-analysis': typeof GapAnalysisRoute
  '/learning-paths': typeof LearningPathsRoute
  '/mentoring': typeof MentoringRoute
  '/model-reference': typeof ModelReferenceRoute
  '/notices': typeof NoticesRoute
  '/platform-metrics': typeof PlatformMetricsRoute
  '/progression': typeof ProgressionRoute
  '/scoring-rulers': typeof ScoringRulersRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/team-rules': typeof TeamRulesRoute
  '/teams': typeof TeamsRoute
  '/text-templates': typeof TextTemplatesRoute
  '/training-needs': typeof TrainingNeedsRoute
  '/users': typeof UsersRoute
  '/vocabularies': typeof VocabulariesRoute
  '/professionals/$professionalId': typeof ProfessionalsProfessionalIdRouteWithChildren
  '/professionals/$professionalId/evolution': typeof ProfessionalsProfessionalIdEvolutionRoute
  '/professionals/$professionalId/roadmap': typeof ProfessionalsProfessionalIdRoadmapRoute
  '/professionals/$professionalId/statement': typeof ProfessionalsProfessionalIdStatementRoute
  '/professionals/$professionalId/': typeof ProfessionalsProfessionalIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRoute
  '/calibration': typeof CalibrationRoute
  '/capability-map': typeof CapabilityMapRoute
  '/catalog-policy': typeof CatalogPolicyRoute
  '/compare': typeof CompareRoute
  '/competency-matrix': typeof CompetencyMatrixRoute
  '/cycles': typeof CyclesRoute
  '/development-plans': typeof DevelopmentPlansRoute
  '/eligibility': typeof EligibilityRoute
  '/gap-analysis': typeof GapAnalysisRoute
  '/learning-paths': typeof LearningPathsRoute
  '/mentoring': typeof MentoringRoute
  '/model-reference': typeof ModelReferenceRoute
  '/notices': typeof NoticesRoute
  '/platform-metrics': typeof PlatformMetricsRoute
  '/progression': typeof ProgressionRoute
  '/scoring-rulers': typeof ScoringRulersRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/team-rules': typeof TeamRulesRoute
  '/teams': typeof TeamsRoute
  '/text-templates': typeof TextTemplatesRoute
  '/training-needs': typeof TrainingNeedsRoute
  '/users': typeof UsersRoute
  '/vocabularies': typeof VocabulariesRoute
  '/professionals/$professionalId/evolution': typeof ProfessionalsProfessionalIdEvolutionRoute
  '/professionals/$professionalId/roadmap': typeof ProfessionalsProfessionalIdRoadmapRoute
  '/professionals/$professionalId/statement': typeof ProfessionalsProfessionalIdStatementRoute
  '/professionals/$professionalId': typeof ProfessionalsProfessionalIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRoute
  '/calibration': typeof CalibrationRoute
  '/capability-map': typeof CapabilityMapRoute
  '/catalog-policy': typeof CatalogPolicyRoute
  '/compare': typeof CompareRoute
  '/competency-matrix': typeof CompetencyMatrixRoute
  '/cycles': typeof CyclesRoute
  '/development-plans': typeof DevelopmentPlansRoute
  '/eligibility': typeof EligibilityRoute
  '/gap-analysis': typeof GapAnalysisRoute
  '/learning-paths': typeof LearningPathsRoute
  '/mentoring': typeof MentoringRoute
  '/model-reference': typeof ModelReferenceRoute
  '/notices': typeof NoticesRoute
  '/platform-metrics': typeof PlatformMetricsRoute
  '/progression': typeof ProgressionRoute
  '/scoring-rulers': typeof ScoringRulersRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/team-rules': typeof TeamRulesRoute
  '/teams': typeof TeamsRoute
  '/text-templates': typeof TextTemplatesRoute
  '/training-needs': typeof TrainingNeedsRoute
  '/users': typeof UsersRoute
  '/vocabularies': typeof VocabulariesRoute
  '/professionals/$professionalId': typeof ProfessionalsProfessionalIdRouteWithChildren
  '/professionals/$professionalId/evolution': typeof ProfessionalsProfessionalIdEvolutionRoute
  '/professionals/$professionalId/roadmap': typeof ProfessionalsProfessionalIdRoadmapRoute
  '/professionals/$professionalId/statement': typeof ProfessionalsProfessionalIdStatementRoute
  '/professionals/$professionalId/': typeof ProfessionalsProfessionalIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessments'
    | '/calibration'
    | '/capability-map'
    | '/catalog-policy'
    | '/compare'
    | '/competency-matrix'
    | '/cycles'
    | '/development-plans'
    | '/eligibility'
    | '/gap-analysis'
    | '/learning-paths'
    | '/mentoring'
    | '/model-reference'
    | '/notices'
    | '/platform-metrics'
    | '/progression'
    | '/scoring-rulers'
    | '/set-password'
    | '/settings'
    | '/team'
    | '/team-rules'
    | '/teams'
    | '/text-templates'
    | '/training-needs'
    | '/users'
    | '/vocabularies'
    | '/professionals/$professionalId'
    | '/professionals/$professionalId/evolution'
    | '/professionals/$professionalId/roadmap'
    | '/professionals/$professionalId/statement'
    | '/professionals/$professionalId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessments'
    | '/calibration'
    | '/capability-map'
    | '/catalog-policy'
    | '/compare'
    | '/competency-matrix'
    | '/cycles'
    | '/development-plans'
    | '/eligibility'
    | '/gap-analysis'
    | '/learning-paths'
    | '/mentoring'
    | '/model-reference'
    | '/notices'
    | '/platform-metrics'
    | '/progression'
    | '/scoring-rulers'
    | '/set-password'
    | '/settings'
    | '/team'
    | '/team-rules'
    | '/teams'
    | '/text-templates'
    | '/training-needs'
    | '/users'
    | '/vocabularies'
    | '/professionals/$professionalId/evolution'
    | '/professionals/$professionalId/roadmap'
    | '/professionals/$professionalId/statement'
    | '/professionals/$professionalId'
  id:
    | '__root__'
    | '/'
    | '/assessments'
    | '/calibration'
    | '/capability-map'
    | '/catalog-policy'
    | '/compare'
    | '/competency-matrix'
    | '/cycles'
    | '/development-plans'
    | '/eligibility'
    | '/gap-analysis'
    | '/learning-paths'
    | '/mentoring'
    | '/model-reference'
    | '/notices'
    | '/platform-metrics'
    | '/progression'
    | '/scoring-rulers'
    | '/set-password'
    | '/settings'
    | '/team'
    | '/team-rules'
    | '/teams'
    | '/text-templates'
    | '/training-needs'
    | '/users'
    | '/vocabularies'
    | '/professionals/$professionalId'
    | '/professionals/$professionalId/evolution'
    | '/professionals/$professionalId/roadmap'
    | '/professionals/$professionalId/statement'
    | '/professionals/$professionalId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentsRoute: typeof AssessmentsRoute
  CalibrationRoute: typeof CalibrationRoute
  CapabilityMapRoute: typeof CapabilityMapRoute
  CatalogPolicyRoute: typeof CatalogPolicyRoute
  CompareRoute: typeof CompareRoute
  CompetencyMatrixRoute: typeof CompetencyMatrixRoute
  CyclesRoute: typeof CyclesRoute
  DevelopmentPlansRoute: typeof DevelopmentPlansRoute
  EligibilityRoute: typeof EligibilityRoute
  GapAnalysisRoute: typeof GapAnalysisRoute
  LearningPathsRoute: typeof LearningPathsRoute
  MentoringRoute: typeof MentoringRoute
  ModelReferenceRoute: typeof ModelReferenceRoute
  NoticesRoute: typeof NoticesRoute
  PlatformMetricsRoute: typeof PlatformMetricsRoute
  ProgressionRoute: typeof ProgressionRoute
  ScoringRulersRoute: typeof ScoringRulersRoute
  SetPasswordRoute: typeof SetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  TeamRoute: typeof TeamRoute
  TeamRulesRoute: typeof TeamRulesRoute
  TeamsRoute: typeof TeamsRoute
  TextTemplatesRoute: typeof TextTemplatesRoute
  TrainingNeedsRoute: typeof TrainingNeedsRoute
  UsersRoute: typeof UsersRoute
  VocabulariesRoute: typeof VocabulariesRoute
  ProfessionalsProfessionalIdRoute: typeof ProfessionalsProfessionalIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments': {
      id: '/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calibration': {
      id: '/calibration'
      path: '/calibration'
      fullPath: '/calibration'
      preLoaderRoute: typeof CalibrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capability-map': {
      id: '/capability-map'
      path: '/capability-map'
      fullPath: '/capability-map'
      preLoaderRoute: typeof CapabilityMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog-policy': {
      id: '/catalog-policy'
      path: '/catalog-policy'
      fullPath: '/catalog-policy'
      preLoaderRoute: typeof CatalogPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competency-matrix': {
      id: '/competency-matrix'
      path: '/competency-matrix'
      fullPath: '/competency-matrix'
      preLoaderRoute: typeof CompetencyMatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cycles': {
      id: '/cycles'
      path: '/cycles'
      fullPath: '/cycles'
      preLoaderRoute: typeof CyclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development-plans': {
      id: '/development-plans'
      path: '/development-plans'
      fullPath: '/development-plans'
      preLoaderRoute: typeof DevelopmentPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eligibility': {
      id: '/eligibility'
      path: '/eligibility'
      fullPath: '/eligibility'
      preLoaderRoute: typeof EligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gap-analysis': {
      id: '/gap-analysis'
      path: '/gap-analysis'
      fullPath: '/gap-analysis'
      preLoaderRoute: typeof GapAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-paths': {
      id: '/learning-paths'
      path: '/learning-paths'
      fullPath: '/learning-paths'
      preLoaderRoute: typeof LearningPathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentoring': {
      id: '/mentoring'
      path: '/mentoring'
      fullPath: '/mentoring'
      preLoaderRoute: typeof MentoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-reference': {
      id: '/model-reference'
      path: '/model-reference'
      fullPath: '/model-reference'
      preLoaderRoute: typeof ModelReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform-metrics': {
      id: '/platform-metrics'
      path: '/platform-metrics'
      fullPath: '/platform-metrics'
      preLoaderRoute: typeof PlatformMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progression': {
      id: '/progression'
      path: '/progression'
      fullPath: '/progression'
      preLoaderRoute: typeof ProgressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scoring-rulers': {
      id: '/scoring-rulers'
      path: '/scoring-rulers'
      fullPath: '/scoring-rulers'
      preLoaderRoute: typeof ScoringRulersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-rules': {
      id: '/team-rules'
      path: '/team-rules'
      fullPath: '/team-rules'
      preLoaderRoute: typeof TeamRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-templates': {
      id: '/text-templates'
      path: '/text-templates'
      fullPath: '/text-templates'
      preLoaderRoute: typeof TextTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training-needs': {
      id: '/training-needs'
      path: '/training-needs'
      fullPath: '/training-needs'
      preLoaderRoute: typeof TrainingNeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabularies': {
      id: '/vocabularies'
      path: '/vocabularies'
      fullPath: '/vocabularies'
      preLoaderRoute: typeof VocabulariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professionals/$professionalId': {
      id: '/professionals/$professionalId'
      path: '/professionals/$professionalId'
      fullPath: '/professionals/$professionalId'
      preLoaderRoute: typeof ProfessionalsProfessionalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professionals/$professionalId/': {
      id: '/professionals/$professionalId/'
      path: '/'
      fullPath: '/professionals/$professionalId/'
      preLoaderRoute: typeof ProfessionalsProfessionalIdIndexRouteImport
      parentRoute: typeof ProfessionalsProfessionalIdRoute
    }
    '/professionals/$professionalId/evolution': {
      id: '/professionals/$professionalId/evolution'
      path: '/evolution'
      fullPath: '/professionals/$professionalId/evolution'
      preLoaderRoute: typeof ProfessionalsProfessionalIdEvolutionRouteImport
      parentRoute: typeof ProfessionalsProfessionalIdRoute
    }
    '/professionals/$professionalId/roadmap': {
      id: '/professionals/$professionalId/roadmap'
      path: '/roadmap'
      fullPath: '/professionals/$professionalId/roadmap'
      preLoaderRoute: typeof ProfessionalsProfessionalIdRoadmapRouteImport
      parentRoute: typeof ProfessionalsProfessionalIdRoute
    }
    '/professionals/$professionalId/statement': {
      id: '/professionals/$professionalId/statement'
      path: '/statement'
      fullPath: '/professionals/$professionalId/statement'
      preLoaderRoute: typeof ProfessionalsProfessionalIdStatementRouteImport
      parentRoute: typeof ProfessionalsProfessionalIdRoute
    }
  }
}

interface ProfessionalsProfessionalIdRouteChildren {
  ProfessionalsProfessionalIdEvolutionRoute: typeof ProfessionalsProfessionalIdEvolutionRoute
  ProfessionalsProfessionalIdRoadmapRoute: typeof ProfessionalsProfessionalIdRoadmapRoute
  ProfessionalsProfessionalIdStatementRoute: typeof ProfessionalsProfessionalIdStatementRoute
  ProfessionalsProfessionalIdIndexRoute: typeof ProfessionalsProfessionalIdIndexRoute
}

const ProfessionalsProfessionalIdRouteChildren: ProfessionalsProfessionalIdRouteChildren =
  {
    ProfessionalsProfessionalIdEvolutionRoute:
      ProfessionalsProfessionalIdEvolutionRoute,
    ProfessionalsProfessionalIdRoadmapRoute:
      ProfessionalsProfessionalIdRoadmapRoute,
    ProfessionalsProfessionalIdStatementRoute:
      ProfessionalsProfessionalIdStatementRoute,
    ProfessionalsProfessionalIdIndexRoute:
      ProfessionalsProfessionalIdIndexRoute,
  }

const ProfessionalsProfessionalIdRouteWithChildren =
  ProfessionalsProfessionalIdRoute._addFileChildren(
    ProfessionalsProfessionalIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentsRoute: AssessmentsRoute,
  CalibrationRoute: CalibrationRoute,
  CapabilityMapRoute: CapabilityMapRoute,
  CatalogPolicyRoute: CatalogPolicyRoute,
  CompareRoute: CompareRoute,
  CompetencyMatrixRoute: CompetencyMatrixRoute,
  CyclesRoute: CyclesRoute,
  DevelopmentPlansRoute: DevelopmentPlansRoute,
  EligibilityRoute: EligibilityRoute,
  GapAnalysisRoute: GapAnalysisRoute,
  LearningPathsRoute: LearningPathsRoute,
  MentoringRoute: MentoringRoute,
  ModelReferenceRoute: ModelReferenceRoute,
  NoticesRoute: NoticesRoute,
  PlatformMetricsRoute: PlatformMetricsRoute,
  ProgressionRoute: ProgressionRoute,
  ScoringRulersRoute: ScoringRulersRoute,
  SetPasswordRoute: SetPasswordRoute,
  SettingsRoute: SettingsRoute,
  TeamRoute: TeamRoute,
  TeamRulesRoute: TeamRulesRoute,
  TeamsRoute: TeamsRoute,
  TextTemplatesRoute: TextTemplatesRoute,
  TrainingNeedsRoute: TrainingNeedsRoute,
  UsersRoute: UsersRoute,
  VocabulariesRoute: VocabulariesRoute,
  ProfessionalsProfessionalIdRoute:
    ProfessionalsProfessionalIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
