/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssessmentsRouteImport } from './routes/assessments'
import { Route as CapabilityMapRouteImport } from './routes/capability-map'
import { Route as CompetencyMatrixRouteImport } from './routes/competency-matrix'
import { Route as CyclesRouteImport } from './routes/cycles'
import { Route as DevelopmentPlansRouteImport } from './routes/development-plans'
import { Route as GapAnalysisRouteImport } from './routes/gap-analysis'
import { Route as LearningPathsRouteImport } from './routes/learning-paths'
import { Route as MentoringRouteImport } from './routes/mentoring'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TalentMatrixRouteImport } from './routes/talent-matrix'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TrainingNeedsRouteImport } from './routes/training-needs'
import { Route as ArchitectsArchitectIdRouteImport } from './routes/architects.$architectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsRoute = AssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilityMapRoute = CapabilityMapRouteImport.update({
  id: '/capability-map',
  path: '/capability-map',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetencyMatrixRoute = CompetencyMatrixRouteImport.update({
  id: '/competency-matrix',
  path: '/competency-matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const CyclesRoute = CyclesRouteImport.update({
  id: '/cycles',
  path: '/cycles',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentPlansRoute = DevelopmentPlansRouteImport.update({
  id: '/development-plans',
  path: '/development-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const GapAnalysisRoute = GapAnalysisRouteImport.update({
  id: '/gap-analysis',
  path: '/gap-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningPathsRoute = LearningPathsRouteImport.update({
  id: '/learning-paths',
  path: '/learning-paths',
  getParentRoute: () => rootRouteImport,
} as any)
const MentoringRoute = MentoringRouteImport.update({
  id: '/mentoring',
  path: '/mentoring',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentMatrixRoute = TalentMatrixRouteImport.update({
  id: '/talent-matrix',
  path: '/talent-matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingNeedsRoute = TrainingNeedsRouteImport.update({
  id: '/training-needs',
  path: '/training-needs',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectsArchitectIdRoute = ArchitectsArchitectIdRouteImport.update({
  id: '/architects/$architectId',
  path: '/architects/$architectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRoute
  '/capability-map': typeof CapabilityMapRoute
  '/competency-matrix': typeof CompetencyMatrixRoute
  '/cycles': typeof CyclesRoute
  '/development-plans': typeof DevelopmentPlansRoute
  '/gap-analysis': typeof GapAnalysisRoute
  '/learning-paths': typeof LearningPathsRoute
  '/mentoring': typeof MentoringRoute
  '/settings': typeof SettingsRoute
  '/talent-matrix': typeof TalentMatrixRoute
  '/team': typeof TeamRoute
  '/training-needs': typeof TrainingNeedsRoute
  '/architects/$architectId': typeof ArchitectsArchitectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRoute
  '/capability-map': typeof CapabilityMapRoute
  '/competency-matrix': typeof CompetencyMatrixRoute
  '/cycles': typeof CyclesRoute
  '/development-plans': typeof DevelopmentPlansRoute
  '/gap-analysis': typeof GapAnalysisRoute
  '/learning-paths': typeof LearningPathsRoute
  '/mentoring': typeof MentoringRoute
  '/settings': typeof SettingsRoute
  '/talent-matrix': typeof TalentMatrixRoute
  '/team': typeof TeamRoute
  '/training-needs': typeof TrainingNeedsRoute
  '/architects/$architectId': typeof ArchitectsArchitectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRoute
  '/capability-map': typeof CapabilityMapRoute
  '/competency-matrix': typeof CompetencyMatrixRoute
  '/cycles': typeof CyclesRoute
  '/development-plans': typeof DevelopmentPlansRoute
  '/gap-analysis': typeof GapAnalysisRoute
  '/learning-paths': typeof LearningPathsRoute
  '/mentoring': typeof MentoringRoute
  '/settings': typeof SettingsRoute
  '/talent-matrix': typeof TalentMatrixRoute
  '/team': typeof TeamRoute
  '/training-needs': typeof TrainingNeedsRoute
  '/architects/$architectId': typeof ArchitectsArchitectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessments'
    | '/capability-map'
    | '/competency-matrix'
    | '/cycles'
    | '/development-plans'
    | '/gap-analysis'
    | '/learning-paths'
    | '/mentoring'
    | '/settings'
    | '/talent-matrix'
    | '/team'
    | '/training-needs'
    | '/architects/$architectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessments'
    | '/capability-map'
    | '/competency-matrix'
    | '/cycles'
    | '/development-plans'
    | '/gap-analysis'
    | '/learning-paths'
    | '/mentoring'
    | '/settings'
    | '/talent-matrix'
    | '/team'
    | '/training-needs'
    | '/architects/$architectId'
  id:
    | '__root__'
    | '/'
    | '/assessments'
    | '/capability-map'
    | '/competency-matrix'
    | '/cycles'
    | '/development-plans'
    | '/gap-analysis'
    | '/learning-paths'
    | '/mentoring'
    | '/settings'
    | '/talent-matrix'
    | '/team'
    | '/training-needs'
    | '/architects/$architectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentsRoute: typeof AssessmentsRoute
  CapabilityMapRoute: typeof CapabilityMapRoute
  CompetencyMatrixRoute: typeof CompetencyMatrixRoute
  CyclesRoute: typeof CyclesRoute
  DevelopmentPlansRoute: typeof DevelopmentPlansRoute
  GapAnalysisRoute: typeof GapAnalysisRoute
  LearningPathsRoute: typeof LearningPathsRoute
  MentoringRoute: typeof MentoringRoute
  SettingsRoute: typeof SettingsRoute
  TalentMatrixRoute: typeof TalentMatrixRoute
  TeamRoute: typeof TeamRoute
  TrainingNeedsRoute: typeof TrainingNeedsRoute
  ArchitectsArchitectIdRoute: typeof ArchitectsArchitectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments': {
      id: '/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capability-map': {
      id: '/capability-map'
      path: '/capability-map'
      fullPath: '/capability-map'
      preLoaderRoute: typeof CapabilityMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competency-matrix': {
      id: '/competency-matrix'
      path: '/competency-matrix'
      fullPath: '/competency-matrix'
      preLoaderRoute: typeof CompetencyMatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cycles': {
      id: '/cycles'
      path: '/cycles'
      fullPath: '/cycles'
      preLoaderRoute: typeof CyclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development-plans': {
      id: '/development-plans'
      path: '/development-plans'
      fullPath: '/development-plans'
      preLoaderRoute: typeof DevelopmentPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gap-analysis': {
      id: '/gap-analysis'
      path: '/gap-analysis'
      fullPath: '/gap-analysis'
      preLoaderRoute: typeof GapAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-paths': {
      id: '/learning-paths'
      path: '/learning-paths'
      fullPath: '/learning-paths'
      preLoaderRoute: typeof LearningPathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentoring': {
      id: '/mentoring'
      path: '/mentoring'
      fullPath: '/mentoring'
      preLoaderRoute: typeof MentoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent-matrix': {
      id: '/talent-matrix'
      path: '/talent-matrix'
      fullPath: '/talent-matrix'
      preLoaderRoute: typeof TalentMatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training-needs': {
      id: '/training-needs'
      path: '/training-needs'
      fullPath: '/training-needs'
      preLoaderRoute: typeof TrainingNeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architects/$architectId': {
      id: '/architects/$architectId'
      path: '/architects/$architectId'
      fullPath: '/architects/$architectId'
      preLoaderRoute: typeof ArchitectsArchitectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentsRoute: AssessmentsRoute,
  CapabilityMapRoute: CapabilityMapRoute,
  CompetencyMatrixRoute: CompetencyMatrixRoute,
  CyclesRoute: CyclesRoute,
  DevelopmentPlansRoute: DevelopmentPlansRoute,
  GapAnalysisRoute: GapAnalysisRoute,
  LearningPathsRoute: LearningPathsRoute,
  MentoringRoute: MentoringRoute,
  SettingsRoute: SettingsRoute,
  TalentMatrixRoute: TalentMatrixRoute,
  TeamRoute: TeamRoute,
  TrainingNeedsRoute: TrainingNeedsRoute,
  ArchitectsArchitectIdRoute: ArchitectsArchitectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
